---
- name: Poll Dynatrace Problems API
  hosts: localhost

  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ DYNATRACE_HOST }}"
        dt_api_token: "{{ DYNATRACE_API_TOKEN }}"
        delay: 1

  rules:
    - name: Launch Remediation Job Template
      condition:
        all:
          - event.status == "OPEN"
      action:
        run_job_template:
          name: EDA // Dynatrace Problems
          organization: Autodotes
          job_args:
            extra_vars:
              problem_id: "{{ event.problemId }}"
