---
- name: Poll Dynatrace Problems API
  hosts: all

  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ DYNATRACE_HOST }}"
        dt_api_token: "{{ DYNATRACE_API_TOKEN }}"
        delay: 30

  rules:
    # Commands to generate mock disk consumption
    # (linux)    fallocate -l 4G dummy.img
    # (windows)  $file = [System.IO.File]::Create("C:\users\ec2-user\dummylarge.txt"); $file.SetLength(10GB); $file.Close();
    - name: Launch Free Disk Space Remediation
      condition: >-
        event.payload is defined and
        event.status == "OPEN" and
        event.title == 'Free Disk Space Below 30%'
      action:
        run_job_template:
          name: EDA // Resize EBS Volume
          organization: Autodotes
          job_args:
            extra_vars:
              _host: "{{ event['impactedEntities'][0]['name'] }}"

    - name: Launch Generic Remediation Fact Gathering
      # Crawl, walk, run - hone in on specific problem types using conditions
      condition:
        all:
          - event.status == "OPEN"
      action:
        run_job_template:
          name: EDA // Dynatrace Problems
          organization: Autodotes
