---
- name: Poll Dynatrace Problems API
  hosts: all

  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ DYNATRACE_HOST }}"
        dt_api_token: "{{ DYNATRACE_API_TOKEN }}"
        delay: 30

  rules:
    - name: Launch Remediation Job Template
      # Crawl, walk, run - hone in on specific problem types using conditions
      condition:
        all:
          - event.status == "OPEN"
      action:
        run_job_template:
          name: EDA // No-Op
          organization: Autodotes
