---
- name: Watch for new snow records and alerts
  hosts: localhost

  sources:
    - cloin.servicenow.new_records:
        instance: "{{ SN_HOST }}"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        table: sc_req_item
        interval: 1

  rules:
    - name: Debug
      condition: event.sys_id is defined
      action:
        run_playbook:
          name: no_op.yml
