---
- name: Remediate linux demo site
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003
  rules:
    - name: Launch Remediation Job
      condition: >-
        event.payload is defined and
        event.payload._hosts is defined
      action:
        run_job_template:
          name: EDA // Linux Remediation
          organization: Autodotes
          job_args:
            extra_vars:
              _hosts: "{{ event.payload._hosts }}"
